name: deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'bin/**'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      #lets us access repo under ${GITHUB_WORKSPACE}
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          #whole git history
          fetch-depth: 0
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          ssh_private_key: ${{ secrets.SFTP_PKEY }}
          remote_path: './stack/wordpress/'
            
            
